### ISSUE TITLE
Feature Request: Add more page snippets

### ISSUE THREAD

**Issue by doggy8088** [jaktestowac/vscode-playwright-snippets#1]
The `page.routeFromHAR` API is quite good, it is recommended to add to snippets.

For example:

```js
await page.routeFromHAR('./hars/fruits.har', {
  url: '*/**/api/v1/fruits',
  update: true,
});
```

https://github.com/microsoft/playwright-examples/blob/4eb82aedf58321da90332e5f7316b64d5914a6b1/tests/api-mocking/api-mocking.spec.ts#L46-L49

**Comment by Freudenberger** [comment]
In v0.0.21 added:
- `pw-record-har`
- `pw-use-har`
