### ISSUE TITLE
Please update CHANGELOG.md accordingly

### ISSUE THREAD

**Issue by doggy8088** [jaktestowac/vscode-playwright-snippets#2]
I think this extension is awesome. I'd like to request a proper CHANGELOG.md for better understanding what's changed. Thanks. :)

**Comment by Freudenberger** [comment]
Thank You very much!🙇‍♂️
And I totally agree about CHANGELOG! 
While we are after MVP - we definitely should take care of that 😉

**Comment by Freudenberger** [comment]
I filled changelog and I will be keeping it up to date :)
